version: "3.7"

services:
  database:
    image: mysql
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=datashowpass
      - MYSQL_DATABASE=datashow
    volumes:
      - .mysql:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    container_name: datashow
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database
    networks:
      - backend
    links:
      - "database"

volumes:
  pgdata:
    driver: local

networks:
  backend:
    driver: bridge