version: "3.7"

services:
  database:
    image: postgres:16.0
    container_name: datashow_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=datashow
      - POSTGRES_PASSWORD=datashowpass
      - POSTGRES_DB=datashow
    volumes:
      - .postgres:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: datashow_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database
    networks:
      - backend
    links:
      - "database"

volumes:
  pgdata:
    driver: local

networks:
  backend:
    driver: bridge
